### ISSUE TITLE
Favicons have now been added into SearXNG

### ISSUE THREAD

**Issue by vojkovic** [Iliano101/neosearch-favicons#1]
We have just merged https://github.com/searxng/searxng/commit/e17d7632d0ed8284c218f65604ab5fa5d4b8ff81

I predict this change will have a breaking impact on this extension.

**Comment by ilianoKokoro** [comment]
Hey there,
I not even sure how you found my extension since it literally has 1 user, but thanks for the heads-up. 
I just fixed it in v3.0 that will be published very soon.
